import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { Poppins } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "400", "500"],
  variable: "--font-poppins",
});

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReactQueryWrapper from "@/components/ReactQueryWrapper";
import { AccountSuper } from "@/components/Super";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={`${poppins.variable} font-sans bg-slate-100`}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <ReactQueryWrapper>
          <Navbar />
          <div className="pt-20">{children}</div>
          <Footer />
          <AccountSuper />
        </ReactQueryWrapper>
      </body>
    </html>
  );
}
